// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dkvrsnuibgipdekztqhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdnJzbnVpYmdpcGRla3p0cWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjUzNDUsImV4cCI6MjA3MzE0MTM0NX0.NVTVhS5se-2T0THI8qKNQzsv3BKdmJnJOwrWSkNsg1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);